### ISSUE TITLE
Crash when pushing left star leftward

### ISSUE THREAD

**Issue by bruab** [mkb0517/myGame#1]
I ran the game

    python starpusher.py

and pressed the left arrow key. This is what I got:

```
Traceback (most recent call last):
  File "starpusher.py", line 635, in <module>
    main()
  File "starpusher.py", line 112, in main
    result = runLevel(levels, currentLevelIndex)
  File "starpusher.py", line 217, in runLevel
    moved = makeMove(mapObj, gameStateObj, playerMoveTo)
  File "starpusher.py", line 395, in makeMove
    if not isBlocked(mapObj, gameStateObj, playerx + (xOffset*2), playery + (yOffset*2)):
  File "starpusher.py", line 344, in isBlocked
    elif isNPC(gameStateObj, x, y):
  File "starpusher.py", line 284, in isNPC
    if x < 0 or x >= len(gameStateObj) or y < 0 or y >= len(gameStateObj[x]):
KeyError: 2
```

**Comment by bruab** [comment]
Oops, sorry:

OS X 10.10.5 Yosemite, Anaconda 2.3.0, Python 2.7.10

**Comment by mkb0517** [comment]
You were right, changing the gameStateObj to mapObj fixed the crashing
